steps:
  # Step 1: Akses Service Key dari Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ambil service key dari Secret Manager
        gcloud secrets versions access latest --secret=credentials > /workspace/destinasyik-ML.json

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/destinasyikreccomenders'
      - '.'

  # Step 3: Push Docker image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/destinasyikreccomenders'

  # Step 4: Deploy ke Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/destinasyikreccomenders'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/app/destinasyik-ML.json'

substitutions:
  _SERVICE_NAME: 'destinasyikreccomenders-service'